const character_data = {
    races: {
        Dwarf: {
            str: 40,
            con: 30,
            dex: 25,
            wis: 25,
            res: 30,
            hp: 8,
            hp_dice:1,
        },
        Elf: {
            str: 25,
            con: 20,
            dex: 40,
            wis: 35,
            res: 30,
            hp: 6,
            hp_dice:1,
        },
        Halfling: {
            str: 20,
            con: 20,
            dex: 40,
            wis: 30,
            res: 40,
            hp: 5,
        },
        Human: {
            str: 30,
            con: 30,
            dex: 30,
            wis: 30,
            res: 30,
            hp: 7,
            hp_dice:1,
        },
        "Half-Ogre": {
            str: 50,
            con: 40,
            dex: 25,
            wis: 15,
            res: 40,
            hp: 10,
            hp_dice:2,
        },
        Duckfolk: {
            str: 25,
            con: 25,
            dex: 30,
            wis: 30,
            res: 40,
            hp: 6,
            hp_dice:1,
        },
    },

    professions: {
        Alchemist: {
            cs: -5,
            rs: -5,
            dodge: -10,
            picklocks: -20,
            barter: 0,
            heal: 5,
            alchemy: 10,
            perception: -10,
            arcane: "NA",
            forage: -20,
            prayer: "NA",
            bonus_hp: 0,
        },
        Barbarian: {
            cs: 15,
            rs: -10,
            dodge: 5,
            picklocks: -20,
            barter: -15,
            heal: -10,
            alchemy: -25,
            perception: -5,
            arcane: "NA",
            forage: -15,
            prayer: "NA",
            bonus_hp: 2,
        },
        Warrior: {
            cs: 10,
            rs: 5,
            dodge: 0,
            picklocks: -20,
            barter: -15,
            heal: -10,
            alchemy: -25,
            perception: -10,
            arcane: "NA",
            forage: -15,
            prayer: "NA",
            bonus_hp: 3,
        },
        Ranger: {
            cs: -5,
            rs: 15,
            dodge: -5,
            picklocks: -25,
            barter: -20,
            heal: -10,
            alchemy: -20,
            perception: 0,
            arcane: "NA",
            forage: 15,
            prayer: "NA",
            bonus_hp: 0,
        },
        Rogue: {
            cs: 0,
            rs: 0,
            dodge: 0,
            picklocks: -5,
            barter: 5,
            heal: -10,
            alchemy: -25,
            perception: 0,
            arcane: "NA",
            forage: 0,
            prayer: "NA",
            bonus_hp: 1,
        },
        Thief: {
            cs: -5,
            rs: 5,
            dodge: 5,
            picklocks: 10,
            barter: 0,
            heal: -20,
            alchemy: -30,
            perception: 10,
            arcane: "NA",
            forage: -20,
            prayer: "NA",
            bonus_hp: 0,
        },
        "Warrior Priest": {
            cs: 5,
            rs: -5,
            dodge: -5,
            picklocks: -20,
            barter: -10,
            heal: 5,
            alchemy: -15,
            perception: -10,
            arcane: "NA",
            forage: -20,
            prayer: 15,
            bonus_hp: 1,
        },
        Wizard: {
            cs: -5,
            rs: -10,
            dodge: -10,
            picklocks: -20,
            barter: 5,
            heal: -5,
            alchemy: -20,
            perception: -10,
            arcane: 10,
            forage: -20,
            prayer: "NA",
            bonus_hp: 0,
        },
        Druid: {
            cs: -5,
            rs: 0,
            dodge: -10,
            picklocks: -20,
            barter: 0,
            heal: 5,
            alchemy: 0,
            perception: -5,
            arcane: 5,
            forage: 0,
            prayer: "NA",
            bonus_hp: 0,
        },
        Knight: {
            cs: 10,
            rs: "NA",
            dodge: 0,
            picklocks: -25,
            barter: 5,
            heal: -15,
            alchemy: -20,
            perception: -10,
            arcane: "NA",
            forage: -25,
            prayer: "NA",
            bonus_hp: 2,
        },
    },

    bonuses: {
        maxBonusPoints: 15,
        maxPerStat: 10,
        freeSkillBonus: 10,
    },
};
